plugin: aws_ec2
regions:
  - "us-east-1"
filters:
  tag:stack: ansible_project  # 4 instance'da da var bu tag
keyed_groups:
  - key: tags.Name  # isme göre grupla
  - key: tags.environment # environment ismine göre grupla
compose:
  ansible_host: public_ip_address